### ISSUE TITLE
Bump jest from 26.6.3 to 27.0.3

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#5241]
@dependabot failed to upgrade jest in https://github.com/internetarchive/openlibrary/pull/5240

Errors include `    ReferenceError: localStorage is not defined` and issues relating to jQuery (TypeError: $.extend is not a function and  `    jQuery requires a window with a document`

Someone should manually upgrade this library and make the required adjustments to the existing tests  to keep them running and passing as before.

### Steps to Reproduce

* Upgrade jest
* Run `test:js`
* Fix issues

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@jdlrobson

**Comment by Yashs911** [comment]
I updated the jest to the latest version (27.0.4) and ran the `npm run test` but I didn't get any errors.
![image](https://user-images.githubusercontent.com/64412143/120930819-8cc22200-c70c-11eb-852b-f357b86deda4.png)

**Comment by jdlrobson** [comment]
Do you want to push up a patch?
