### PR TITLE
Fix 'ThreadedDict' object has no attribute 'site' in web.py fulltext search

### LINKED ISSUE #11653: Error in Partials/Search Inside endpoints (master but not prod)
### Problem

`'ThreadedDict' object has no attribute 'site'` is occurring on localhost and testing.
I used git bisect to narrow it down to this PR: https://github.com/internetarchive/openlibrary/pull/11521/changes

I didn't dig into it yet but it's likely because we're trying to access some variables from an webpy -> async context. In the fully async context everything seems fine.

This is probably blocking deploy so a high priority: cc @cdrini 

The search inside code is less important since we are fully fastapi on that and we could just delete that endpoint.
However, that it's broken for partials is an issue.

Broken links (webpy):
http://localhost:8080/search/inside.json?q=%22I+call+our+world+Flatland%2C+not+because+we+call+it+so%2C+but+to+make+its+nature+clearer+to+you%2C+my+happy+readers%2C+who+are+privileged+to+live+in+Space.%22&mode=everything&offset=1
http://localhost:8080/partials.json?_component=FulltextSearchSuggestion&data=%22I+call+our+world+Flatland%2C+not+because+we+call+it+so%2C+but+to+make+its+nature+clearer+to+you%2C+my+happy+readers%2C+who+are+privileged+to+live+in+Space.%22

Both are fine in fastapi:
http://localhost:18080/search/inside.json?q=%22I+call+our+world+Flatland%2C+not+because+we+call+it+so%2C+but+to+make+its+nature+clearer+to+you%2C+my+happy+readers%2C+who+are+privileged+to+live+in+Space.%22&mode=everything&offset=1
http://localhost:18080/partials.json?_component=FulltextSearchSuggestion&data=%22I+call+our+world+Flatland%2C+not+because+we+call+it+so%2C+but+to+make+its+nature+clearer+to+you%2C+my+happy+readers%2C+who+are+privileged+to+live+in+Space.%22

Drini first reported this here:
https://github.com/internetarchive/openlibrary/pull/11634/changes#r2658252716

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

* @cdrini 
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by RayBB**
Closes #11653

### CODE REVIEW

**Comment by mekarpeles** [comment]
Lgtm
