### ISSUE TITLE
Cannot add links

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1795]
## Description
> What problem are we solving?
Go to https://openlibrary.org/works/OL69382W/Essays/edit and click links tab -  I cannot add new links.

A similar problem happens on
https://openlibrary.org/books/OL7885696M/Charlotte's_Web/edit when I try to add contributors and ID numbers.

## Evidence 
> What does the experience look like today? What are the symptoms?

Instead of UI feedback I get a JS error:
```
all.js?v=917fb37afce68c33baea274ee6e9669e:92 Uncaught TypeError: text.replace is not a function
    at htmlquote (all.js?v=917fb37afce68c33baea274ee6e9669e:92)
    at eval (eval at Template (all.js?v=917fb37afce68c33baea274ee6e9669e:280), <anonymous>:14:9)
    at g (all.js?v=917fb37afce68c33baea274ee6e9669e:280)
    at HTMLInputElement.onAdd (all.js?v=917fb37afce68c33baea274ee6e9669e:72)
    at HTMLDocument.dispatch (vendor-v2.js?v=308865190cde0bcd92efd2797951230f:3)
    at HTMLDocument.r.handle (vendor-v2.js?v=308865190cde0bcd92efd2797951230f:3)
```
> Relevant url:

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details
> What page(s) are impacted?
e.g. `https://openlibrary.org/...`

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

## Constraints
> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by jdlrobson** [comment]
Caused by 2f58b99993d275830fd813992720df3389e29020

Turns out the deleted function did not quite match the one in https://github.com/internetarchive/openlibrary/blob/2f58b99993d275830fd813992720df3389e29020/openlibrary/plugins/openlibrary/js/jsdef.js

Let's move the missing logic into the jsdef definition

**Comment by jdlrobson** [comment]
Even better let's work out why text = String(text) is needed and fix at the callef. Are we passing an integer?
