### PR TITLE
Bump jest from 26.6.3 to 27.0.4

### LINKED ISSUE #5241: Bump jest from 26.6.3 to 27.0.3
@dependabot failed to upgrade jest in https://github.com/internetarchive/openlibrary/pull/5240

Errors include `    ReferenceError: localStorage is not defined` and issues relating to jQuery (TypeError: $.extend is not a function and  `    jQuery requires a window with a document`

Someone should manually upgrade this library and make the required adjustments to the existing tests  to keep them running and passing as before.

### Steps to Reproduce

* Upgrade jest
* Run `test:js`
* Fix issues

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@jdlrobson

### PR DESCRIPTION
**Pull request by Yashs911**
Closes #5241 

### Technical

Bump jest from 26.6.3 to 27.0.4
### Testing

`npm run test`
### Screenshot

image

### Stakeholders

@jdlrobson

### CODE REVIEW

**Comment by jdlrobson** [comment]
Looks like a few tests need changing? Can you replicate this locally? If not there might be a global install of npm that is conflicting

**Comment by jdlrobson** [comment]
@Yashs911 I can replicate the errors.

According to the error:
```
    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
```

We can fix this by adding
```

    "testEnvironment": "jsdom",
```
to package.json

**Comment by Yashs911** [comment]
@jdlrobson Sorry for the delay, Running `npm run test` didn't throw any error for me locally.
I will try adding `"testEnvironment": "jsdom",` to package.json

**Comment by Yashs911** [comment]
Tests passed 🎉
